### ISSUE TITLE
Converter create dulplicate items in root

### ISSUE THREAD

**Issue by hyskylord** [json-to-proto/json-to-proto.github.io#1]
Hi,

  I noticed that the converter will dulplicate certain items in the .proto file. Haven't looked into the descriptor yet but this seems like a bug.

**Comment by YaroslavPodorvanov** [comment]
@hyskylord show your JSON

**Comment by hyskylord** [comment]
Hi,

  I noticed the issue later, this will happen if my fields contain names that has number as suffix.

  Here is a minimal reproducible example:

{
  "a": {
            "c": {
              "type": "uint32",
              "id": 1
                 }
        },
"a1": {
            "b": {
              "type": "uint32",
              "id": 1
                 }
},
"c": {
            "a": {
              "type": "uint32",
              "id": 1
                 }
}
}

**Comment by YaroslavPodorvanov** [comment]
@hyskylord, i understood what you mean, you right, i will think how to do better

```json
{
  "a": {
    "c": {
      "type": "uint32",
      "id": 1
    }
  },
  "a1": {
    "b": {
      "type": "uint32",
      "id": 1
    }
  },
  "c": {
    "a": {
      "type": "uint32",
      "id": 1
    }
  }
}
```
```protobuf
syntax = "proto3";

message C {
    string type = 1;
    uint32 id = 2;
}

message A {
    C c = 1;
}

message B {
    string type = 1;
    uint32 id = 2;
}

message A1 {
    B b = 1;
}

message A1 {
    string type = 1;
    uint32 id = 2;
}

message C1 {
    A1 a = 1;
}

message SomeMessage {
    A a = 1;
    A1 a1 = 2;
    C1 c = 3;
}
```

same on https://mholt.github.io/json-to-go/

**Comment by YaroslavPodorvanov** [comment]
@hyskylord work for your example
